DELETE FROM kortex_units_fts_v2 WHERE unit_id IN (SELECT id FROM kortex_units WHERE tenant_id = 'default' AND agent_id = '4c2691e8-085b-409b-af80-f8ca441c96db' AND source_ref = 'apps:keystone-os');
DELETE FROM kortex_units WHERE tenant_id = 'default' AND agent_id = '4c2691e8-085b-409b-af80-f8ca441c96db' AND source_ref = 'apps:keystone-os';
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('1b98e309-5df3-4b78-9fec-37aa457667bd', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'definition', 'Keystone OS, en une phrase', '{"term":"Keystone OS","definition":"Keystone (Keystone OS) est un espace de travail modulaire édité par Protein Studio : il réunit des outils métier dans une seule application web installable (PWA), l''utilisateur active uniquement ce dont il a besoin via le K-Store, l''IA est incluse dans l''abonnement (compteur mensuel, pas de jetons), conçu local d''abord et souverain (données métier dans le navigateur, RGPD). IMPORTANT : Keystone n''est PAS un logiciel d''immobilier ni d''un métier unique — c''est un OS d''outils métier, généraliste et modulaire."}', 'Keystone OS, en une phrase
Keystone OS
Keystone (Keystone OS) est un espace de travail modulaire édité par Protein Studio : il réunit des outils métier dans une seule application web installable (PWA), l''utilisateur active uniquement ce dont il a besoin via le K-Store, l''IA est incluse dans l''abonnement (compteur mensuel, pas de jetons), conçu local d''abord et souverain (données métier dans le navigateur, RGPD). IMPORTANT : Keystone n''est PAS un logiciel d''immobilier ni d''un métier unique — c''est un OS d''outils métier, généraliste et modulaire.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('1b98e309-5df3-4b78-9fec-37aa457667bd', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS, en une phrase', 'Keystone OS, en une phrase
Keystone OS
Keystone (Keystone OS) est un espace de travail modulaire édité par Protein Studio : il réunit des outils métier dans une seule application web installable (PWA), l''utilisateur active uniquement ce dont il a besoin via le K-Store, l''IA est incluse dans l''abonnement (compteur mensuel, pas de jetons), conçu local d''abord et souverain (données métier dans le navigateur, RGPD). IMPORTANT : Keystone n''est PAS un logiciel d''immobilier ni d''un métier unique — c''est un OS d''outils métier, généraliste et modulaire.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('dce2f481-6c61-4f99-92cf-f4286da22ba1', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Le produit, ses formules et son fonctionnement', '{"statement":"(Repris du guide utilisateur officiel de Keystone.) Le guide pour tirer le meilleur de Keystone. Chaque outil a en plus sa propre aide (bouton « ? »)."}', 'Keystone OS — Le produit, ses formules et son fonctionnement
(Repris du guide utilisateur officiel de Keystone.) Le guide pour tirer le meilleur de Keystone. Chaque outil a en plus sa propre aide (bouton « ? »).', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('dce2f481-6c61-4f99-92cf-f4286da22ba1', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Le produit, ses formules et son fonctionnement', 'Keystone OS — Le produit, ses formules et son fonctionnement
(Repris du guide utilisateur officiel de Keystone.) Le guide pour tirer le meilleur de Keystone. Chaque outil a en plus sa propre aide (bouton « ? »).');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('7a539da3-4bc2-4ff6-ac20-5b6ba5944244', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Qu''est-ce que Keystone ?', '{"statement":"Keystone réunit vos outils métier dans un seul espace de travail. Au lieu de jongler entre plusieurs applications et abonnements, vous activez ici uniquement ce dont vous avez besoin — comme des applications sur un téléphone. L''intelligence artificielle est incluse: pas de facturation à la consommation ni de jeton à racheter. Un compteur d''usage équitable évite les abus, et vous gardez la main sur vos données."}', 'Keystone OS — Qu''est-ce que Keystone ?
Keystone réunit vos outils métier dans un seul espace de travail. Au lieu de jongler entre plusieurs applications et abonnements, vous activez ici uniquement ce dont vous avez besoin — comme des applications sur un téléphone. L''intelligence artificielle est incluse: pas de facturation à la consommation ni de jeton à racheter. Un compteur d''usage équitable évite les abus, et vous gardez la main sur vos données.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('7a539da3-4bc2-4ff6-ac20-5b6ba5944244', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Qu''est-ce que Keystone ?', 'Keystone OS — Qu''est-ce que Keystone ?
Keystone réunit vos outils métier dans un seul espace de travail. Au lieu de jongler entre plusieurs applications et abonnements, vous activez ici uniquement ce dont vous avez besoin — comme des applications sur un téléphone. L''intelligence artificielle est incluse: pas de facturation à la consommation ni de jeton à racheter. Un compteur d''usage équitable évite les abus, et vous gardez la main sur vos données.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('a2737d02-683a-453e-9e10-8aa3ad0bcb41', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Votre tableau de bord', '{"statement":"Vos outils apparaissent en tuiles sur l''accueil. Un clic ouvre l''outil en plein écran; la flèche en haut à gauche vous ramène au tableau de bord. Réorganiser: glissez-déposez les tuiles pour les ranger à votre goût. Renommer ou retirer: appui long (mobile) ou clic droit (ordinateur) sur une tuile."}', 'Keystone OS — Votre tableau de bord
Vos outils apparaissent en tuiles sur l''accueil. Un clic ouvre l''outil en plein écran; la flèche en haut à gauche vous ramène au tableau de bord. Réorganiser: glissez-déposez les tuiles pour les ranger à votre goût. Renommer ou retirer: appui long (mobile) ou clic droit (ordinateur) sur une tuile.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('a2737d02-683a-453e-9e10-8aa3ad0bcb41', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Votre tableau de bord', 'Keystone OS — Votre tableau de bord
Vos outils apparaissent en tuiles sur l''accueil. Un clic ouvre l''outil en plein écran; la flèche en haut à gauche vous ramène au tableau de bord. Réorganiser: glissez-déposez les tuiles pour les ranger à votre goût. Renommer ou retirer: appui long (mobile) ou clic droit (ordinateur) sur une tuile.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('53afe0fb-8c17-407e-8938-9141ac867b36', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Ajouter ou retirer des outils', '{"statement":"Le K-Store (bouton + ou l''icône boutique) liste tous les outils disponibles dans votre formule. Ouvrez-le pour ajouter un outil à votre tableau de bord, ou le retirer si vous ne l''utilisez plus — votre travail n''est jamais perdu, l''outil revient avec ses données quand vous le réactivez."}', 'Keystone OS — Ajouter ou retirer des outils
Le K-Store (bouton + ou l''icône boutique) liste tous les outils disponibles dans votre formule. Ouvrez-le pour ajouter un outil à votre tableau de bord, ou le retirer si vous ne l''utilisez plus — votre travail n''est jamais perdu, l''outil revient avec ses données quand vous le réactivez.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('53afe0fb-8c17-407e-8938-9141ac867b36', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Ajouter ou retirer des outils', 'Keystone OS — Ajouter ou retirer des outils
Le K-Store (bouton + ou l''icône boutique) liste tous les outils disponibles dans votre formule. Ouvrez-le pour ajouter un outil à votre tableau de bord, ou le retirer si vous ne l''utilisez plus — votre travail n''est jamais perdu, l''outil revient avec ses données quand vous le réactivez.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('727dba80-b124-4729-9b73-b75521f0f8a6', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Vos crédits IA', '{"statement":"Les fonctions d''intelligence artificielle puisent dans un compteur mensuel inclus dans votre abonnement. Il se remet à zéro le 1er de chaque mois. Vous suivez votre consommation dans la section « Crédits IA » de ces réglages; si besoin, un pack ponctuel peut être ajouté. Beaucoup d''actions sont gratuites: lecture vocale, dictée, navigation, et tout ce qui ne fait pas appel à l''IA."}', 'Keystone OS — Vos crédits IA
Les fonctions d''intelligence artificielle puisent dans un compteur mensuel inclus dans votre abonnement. Il se remet à zéro le 1er de chaque mois. Vous suivez votre consommation dans la section « Crédits IA » de ces réglages; si besoin, un pack ponctuel peut être ajouté. Beaucoup d''actions sont gratuites: lecture vocale, dictée, navigation, et tout ce qui ne fait pas appel à l''IA.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('727dba80-b124-4729-9b73-b75521f0f8a6', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Vos crédits IA', 'Keystone OS — Vos crédits IA
Les fonctions d''intelligence artificielle puisent dans un compteur mensuel inclus dans votre abonnement. Il se remet à zéro le 1er de chaque mois. Vous suivez votre consommation dans la section « Crédits IA » de ces réglages; si besoin, un pack ponctuel peut être ajouté. Beaucoup d''actions sont gratuites: lecture vocale, dictée, navigation, et tout ce qui ne fait pas appel à l''IA.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('1897eeab-9262-4878-a6dc-ed13c6bc85fe', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Vos données & votre confidentialité', '{"statement":"Keystone est conçu local d''abord: vos clés et vos données métier restent dans votre navigateur, sur votre appareil. Seul votre profil (prénom, photo, préférences) est synchronisé, chiffré, pour vous retrouver d''un appareil à l''autre. Le détail complet et le bouton « droit à l''oubli » sont dans la section « RGPD & Données » ci-dessous."}', 'Keystone OS — Vos données & votre confidentialité
Keystone est conçu local d''abord: vos clés et vos données métier restent dans votre navigateur, sur votre appareil. Seul votre profil (prénom, photo, préférences) est synchronisé, chiffré, pour vous retrouver d''un appareil à l''autre. Le détail complet et le bouton « droit à l''oubli » sont dans la section « RGPD & Données » ci-dessous.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('1897eeab-9262-4878-a6dc-ed13c6bc85fe', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Vos données & votre confidentialité', 'Keystone OS — Vos données & votre confidentialité
Keystone est conçu local d''abord: vos clés et vos données métier restent dans votre navigateur, sur votre appareil. Seul votre profil (prénom, photo, préférences) est synchronisé, chiffré, pour vous retrouver d''un appareil à l''autre. Le détail complet et le bouton « droit à l''oubli » sont dans la section « RGPD & Données » ci-dessous.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('e40e474e-be64-4323-888e-e63c9cc1f178', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Installer Keystone sur votre appareil', '{"statement":"Keystone est une application web: rien à télécharger sur un store. Pour l''avoir à portée de main: Sur mobile: menu du navigateur → « Ajouter à l''écran d''accueil ». Sur ordinateur: icône d''installation dans la barre d''adresse, ou menu du navigateur → « Installer ». Une fois installée, elle s''ouvre comme une vraie app et reste consultable même hors connexion pour l''essentiel."}', 'Keystone OS — Installer Keystone sur votre appareil
Keystone est une application web: rien à télécharger sur un store. Pour l''avoir à portée de main: Sur mobile: menu du navigateur → « Ajouter à l''écran d''accueil ». Sur ordinateur: icône d''installation dans la barre d''adresse, ou menu du navigateur → « Installer ». Une fois installée, elle s''ouvre comme une vraie app et reste consultable même hors connexion pour l''essentiel.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('e40e474e-be64-4323-888e-e63c9cc1f178', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Installer Keystone sur votre appareil', 'Keystone OS — Installer Keystone sur votre appareil
Keystone est une application web: rien à télécharger sur un store. Pour l''avoir à portée de main: Sur mobile: menu du navigateur → « Ajouter à l''écran d''accueil ». Sur ordinateur: icône d''installation dans la barre d''adresse, ou menu du navigateur → « Installer ». Une fois installée, elle s''ouvre comme une vraie app et reste consultable même hors connexion pour l''essentiel.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('57e3272e-5027-4843-b7d1-66c083e4cc60', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Les formules', '{"statement":"Votre formule détermine les outils accessibles: Démo (découverte), Starter, Pro et Max (accès complet). Le badge coloré d''un outil dans le K-Store indique la formule requise. Votre statut, votre clé et votre renouvellement sont dans la section « Ma Licence »."}', 'Keystone OS — Les formules
Votre formule détermine les outils accessibles: Démo (découverte), Starter, Pro et Max (accès complet). Le badge coloré d''un outil dans le K-Store indique la formule requise. Votre statut, votre clé et votre renouvellement sont dans la section « Ma Licence ».', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('57e3272e-5027-4843-b7d1-66c083e4cc60', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Les formules', 'Keystone OS — Les formules
Votre formule détermine les outils accessibles: Démo (découverte), Starter, Pro et Max (accès complet). Le badge coloré d''un outil dans le K-Store indique la formule requise. Votre statut, votre clé et votre renouvellement sont dans la section « Ma Licence ».');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('d5bdf077-d5af-49fd-a26a-360931f7f744', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Les offres — 3 plans (c''est ainsi que Keystone se vend)', '{"statement":"Keystone ne se vend pas application par application. Le client choisit un plan, puis active le nombre d''applications que ce plan autorise (3, 5, ou toutes). L''IA (crédits mensuels inclus) et l''hébergement européen font partie du plan — pas de surcoût à l''usage."}', 'Keystone OS — Les offres — 3 plans (c''est ainsi que Keystone se vend)
Keystone ne se vend pas application par application. Le client choisit un plan, puis active le nombre d''applications que ce plan autorise (3, 5, ou toutes). L''IA (crédits mensuels inclus) et l''hébergement européen font partie du plan — pas de surcoût à l''usage.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('d5bdf077-d5af-49fd-a26a-360931f7f744', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Les offres — 3 plans (c''est ainsi que Keystone se vend)', 'Keystone OS — Les offres — 3 plans (c''est ainsi que Keystone se vend)
Keystone ne se vend pas application par application. Le client choisit un plan, puis active le nombre d''applications que ce plan autorise (3, 5, ou toutes). L''IA (crédits mensuels inclus) et l''hébergement européen font partie du plan — pas de surcoût à l''usage.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('f81b97f5-49c1-4767-abc6-538ec9cca8a3', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Starter · 49€/mois', '{"statement":"3 applications au choix 1 utilisateur · 3 appareils 200 crédits IA inclus / mois Connexion à vos IA (Claude, GPT, Mistral…) Export PDF premium Hébergement Europe · RGPD"}', 'Keystone OS — Starter · 49€/mois
3 applications au choix 1 utilisateur · 3 appareils 200 crédits IA inclus / mois Connexion à vos IA (Claude, GPT, Mistral…) Export PDF premium Hébergement Europe · RGPD', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('f81b97f5-49c1-4767-abc6-538ec9cca8a3', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Starter · 49€/mois', 'Keystone OS — Starter · 49€/mois
3 applications au choix 1 utilisateur · 3 appareils 200 crédits IA inclus / mois Connexion à vos IA (Claude, GPT, Mistral…) Export PDF premium Hébergement Europe · RGPD');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('86564f71-8af4-4778-b9af-6c67a665da0a', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Pro · 99€/mois — Populaire', '{"statement":"5 applications au choix 5 utilisateurs · 3 appareils chacun 1 000 crédits IA inclus / mois Connexion à vos IA (Claude, GPT, Mistral…) Export PDF premium Éligible applications sur-mesure"}', 'Keystone OS — Pro · 99€/mois — Populaire
5 applications au choix 5 utilisateurs · 3 appareils chacun 1 000 crédits IA inclus / mois Connexion à vos IA (Claude, GPT, Mistral…) Export PDF premium Éligible applications sur-mesure', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('86564f71-8af4-4778-b9af-6c67a665da0a', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Pro · 99€/mois — Populaire', 'Keystone OS — Pro · 99€/mois — Populaire
5 applications au choix 5 utilisateurs · 3 appareils chacun 1 000 crédits IA inclus / mois Connexion à vos IA (Claude, GPT, Mistral…) Export PDF premium Éligible applications sur-mesure');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('cffaa491-5c97-40f9-9e30-46a56b561c42', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Max · 249€/mois', '{"statement":"Toutes les applications (+ nouveautés incluses) 15 utilisateurs · 3 appareils chacun 5 000 crédits IA inclus / mois Multi-moteur IA — branchez votre propre clé Export PDF premium Support prioritaire dédié"}', 'Keystone OS — Max · 249€/mois
Toutes les applications (+ nouveautés incluses) 15 utilisateurs · 3 appareils chacun 5 000 crédits IA inclus / mois Multi-moteur IA — branchez votre propre clé Export PDF premium Support prioritaire dédié', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('cffaa491-5c97-40f9-9e30-46a56b561c42', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Max · 249€/mois', 'Keystone OS — Max · 249€/mois
Toutes les applications (+ nouveautés incluses) 15 utilisateurs · 3 appareils chacun 5 000 crédits IA inclus / mois Multi-moteur IA — branchez votre propre clé Export PDF premium Support prioritaire dédié');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('e43f836a-a213-4ef3-988f-ef19fa44ea7b', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Gouvernance, RGPD & confiance', '{"statement":"Ce que Keystone garantit côté confiance — de quoi rassurer un prospect, sans entrer dans la technique: RGPD & données. Keystone est conçu local d''abord: les données métier et les clés de l''utilisateur restent sur son appareil; seul le profil (prénom, photo, préférences) est synchronisé et chiffré. Un droit à l''oubli (purge des données) est disponible. L''éditeur est une société française identifiée (Protein Keystone Studio). Les mentions légales, la politique de confidentialité et une page sécurité sont publiées. Prévu à la feuille de route: un export RGPD complet en un clic; aujourd''hui, chaque outil permet déjà d''exporter ses propres données. Avis & commentaires. Chaque outil peut recevoir une note (étoiles) de ses utilisateurs. Les retours sont agrégés de façon anonyme — aucune donnée nominative n''est exposée — et servent à prioriser les améliorations. Posture. L''IA est incluse (pas de revente de données, pas de facturation au jeton, compteur d''usage équitable). Souveraineté et clarté sur les données sont des arguments de vente à part entière. (Le back-office d''administration — licences, réglages internes — est hors de ce document: il ne concerne ni le client ni un plan marketing.)"}', 'Keystone OS — Gouvernance, RGPD & confiance
Ce que Keystone garantit côté confiance — de quoi rassurer un prospect, sans entrer dans la technique: RGPD & données. Keystone est conçu local d''abord: les données métier et les clés de l''utilisateur restent sur son appareil; seul le profil (prénom, photo, préférences) est synchronisé et chiffré. Un droit à l''oubli (purge des données) est disponible. L''éditeur est une société française identifiée (Protein Keystone Studio). Les mentions légales, la politique de confidentialité et une page sécurité sont publiées. Prévu à la feuille de route: un export RGPD complet en un clic; aujourd''hui, chaque outil permet déjà d''exporter ses propres données. Avis & commentaires. Chaque outil peut recevoir une note (étoiles) de ses utilisateurs. Les retours sont agrégés de façon anonyme — aucune donnée nominative n''est exposée — et servent à prioriser les améliorations. Posture. L''IA est incluse (pas de revente de données, pas de facturation au jeton, compteur d''usage équitable). Souveraineté et clarté sur les données sont des arguments de vente à part entière. (Le back-office d''administration — licences, réglages internes — est hors de ce document: il ne concerne ni le client ni un plan marketing.)', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('e43f836a-a213-4ef3-988f-ef19fa44ea7b', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Gouvernance, RGPD & confiance', 'Keystone OS — Gouvernance, RGPD & confiance
Ce que Keystone garantit côté confiance — de quoi rassurer un prospect, sans entrer dans la technique: RGPD & données. Keystone est conçu local d''abord: les données métier et les clés de l''utilisateur restent sur son appareil; seul le profil (prénom, photo, préférences) est synchronisé et chiffré. Un droit à l''oubli (purge des données) est disponible. L''éditeur est une société française identifiée (Protein Keystone Studio). Les mentions légales, la politique de confidentialité et une page sécurité sont publiées. Prévu à la feuille de route: un export RGPD complet en un clic; aujourd''hui, chaque outil permet déjà d''exporter ses propres données. Avis & commentaires. Chaque outil peut recevoir une note (étoiles) de ses utilisateurs. Les retours sont agrégés de façon anonyme — aucune donnée nominative n''est exposée — et servent à prioriser les améliorations. Posture. L''IA est incluse (pas de revente de données, pas de facturation au jeton, compteur d''usage équitable). Souveraineté et clarté sur les données sont des arguments de vente à part entière. (Le back-office d''administration — licences, réglages internes — est hors de ce document: il ne concerne ni le client ni un plan marketing.)');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('978bef26-934d-4d93-8268-097079f70862', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Le Living Layer', '{"statement":"Le Living Layer est une barre ambiante en haut du tableau de bord. Au lieu d''un dashboard figé, il fait remonter en continu de vrais signaux métier issus des outils actifs: les questions auxquelles le Smart Agent n''a pas su répondre (trous de savoir à combler), les réponses reçues, les rappels Keynapse qui arrivent à échéance, les alertes de visibilité Sentinel, le suivi des QR les plus scannés. Une alerte importante reste « collante » tant qu''elle n''est pas traitée. C''est ce qui transforme Keystone d''une boîte à outils en un poste de pilotage qui dit à l''utilisateur quoi faire ensuite."}', 'Keystone OS — Le Living Layer
Le Living Layer est une barre ambiante en haut du tableau de bord. Au lieu d''un dashboard figé, il fait remonter en continu de vrais signaux métier issus des outils actifs: les questions auxquelles le Smart Agent n''a pas su répondre (trous de savoir à combler), les réponses reçues, les rappels Keynapse qui arrivent à échéance, les alertes de visibilité Sentinel, le suivi des QR les plus scannés. Une alerte importante reste « collante » tant qu''elle n''est pas traitée. C''est ce qui transforme Keystone d''une boîte à outils en un poste de pilotage qui dit à l''utilisateur quoi faire ensuite.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('978bef26-934d-4d93-8268-097079f70862', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Le Living Layer', 'Keystone OS — Le Living Layer
Le Living Layer est une barre ambiante en haut du tableau de bord. Au lieu d''un dashboard figé, il fait remonter en continu de vrais signaux métier issus des outils actifs: les questions auxquelles le Smart Agent n''a pas su répondre (trous de savoir à combler), les réponses reçues, les rappels Keynapse qui arrivent à échéance, les alertes de visibilité Sentinel, le suivi des QR les plus scannés. Une alerte importante reste « collante » tant qu''elle n''est pas traitée. C''est ce qui transforme Keystone d''une boîte à outils en un poste de pilotage qui dit à l''utilisateur quoi faire ensuite.');
INSERT INTO kortex_units (id, tenant_id, agent_id, vault_id, type, title, body, body_text, status, source_kind, source_ref, lang) VALUES ('a5d81948-2b9e-4581-b093-545139f999bd', 'default', '4c2691e8-085b-409b-af80-f8ca441c96db', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'fact', 'Keystone OS — Comment les outils travaillent ensemble', '{"statement":"Les outils Keystone ne sont pas des silos: ils se passent le relais. Les enchaînements clés à connaître pour vendre: La chaîne de contenu: Brainstorming fait émerger les idées et tranche les angles → Ghost Writer rédige et met en forme → Social Manager diffuse sur les réseaux. Une idée devient une publication sans changer d''outil. Du physique au conversationnel: un Smart Dynamic QR posé sur une vitrine, un produit ou une chambre d''hôtel ouvre directement un Smart Agent (ou un QR Concierge) qui répond au visiteur — sans app à installer, à l''écrit ou à la voix. La visibilité qui remonte: Sentinel surveille la présence web et l''apparition dans les réponses des IA, et pousse ses alertes dans le Living Layer. Le socle commun: identité de marque (Key Brand), collecte (Key Form), notes et rappels (Keynapse) et transmission de secrets (Missive) servent tous les autres outils. La marque définie dans Key Brand peut habiller les supports produits ailleurs. Le tout dans un seul espace, une seule connexion, un seul abonnement — c''est l''argument central face à quelqu''un qui jongle avec 6 abonnements séparés."}', 'Keystone OS — Comment les outils travaillent ensemble
Les outils Keystone ne sont pas des silos: ils se passent le relais. Les enchaînements clés à connaître pour vendre: La chaîne de contenu: Brainstorming fait émerger les idées et tranche les angles → Ghost Writer rédige et met en forme → Social Manager diffuse sur les réseaux. Une idée devient une publication sans changer d''outil. Du physique au conversationnel: un Smart Dynamic QR posé sur une vitrine, un produit ou une chambre d''hôtel ouvre directement un Smart Agent (ou un QR Concierge) qui répond au visiteur — sans app à installer, à l''écrit ou à la voix. La visibilité qui remonte: Sentinel surveille la présence web et l''apparition dans les réponses des IA, et pousse ses alertes dans le Living Layer. Le socle commun: identité de marque (Key Brand), collecte (Key Form), notes et rappels (Keynapse) et transmission de secrets (Missive) servent tous les autres outils. La marque définie dans Key Brand peut habiller les supports produits ailleurs. Le tout dans un seul espace, une seule connexion, un seul abonnement — c''est l''argument central face à quelqu''un qui jongle avec 6 abonnements séparés.', 'validated', 'import', 'apps:keystone-os', 'fr');
INSERT INTO kortex_units_fts_v2 (unit_id, tenant_id, vault_id, title, body_text) VALUES ('a5d81948-2b9e-4581-b093-545139f999bd', 'default', 'e1dccc3c-7656-4957-bd07-7421857b696c', 'Keystone OS — Comment les outils travaillent ensemble', 'Keystone OS — Comment les outils travaillent ensemble
Les outils Keystone ne sont pas des silos: ils se passent le relais. Les enchaînements clés à connaître pour vendre: La chaîne de contenu: Brainstorming fait émerger les idées et tranche les angles → Ghost Writer rédige et met en forme → Social Manager diffuse sur les réseaux. Une idée devient une publication sans changer d''outil. Du physique au conversationnel: un Smart Dynamic QR posé sur une vitrine, un produit ou une chambre d''hôtel ouvre directement un Smart Agent (ou un QR Concierge) qui répond au visiteur — sans app à installer, à l''écrit ou à la voix. La visibilité qui remonte: Sentinel surveille la présence web et l''apparition dans les réponses des IA, et pousse ses alertes dans le Living Layer. Le socle commun: identité de marque (Key Brand), collecte (Key Form), notes et rappels (Keynapse) et transmission de secrets (Missive) servent tous les autres outils. La marque définie dans Key Brand peut habiller les supports produits ailleurs. Le tout dans un seul espace, une seule connexion, un seul abonnement — c''est l''argument central face à quelqu''un qui jongle avec 6 abonnements séparés.');
